# Generated by Django 5.1.7 on 2025-06-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('CASHIER', 'Cashier'), ('MANAGER', 'Manager'), ('SENIOR_MANAGER', 'Senior Manager'), ('CEO', 'CEO')], help_text='User role in the system', max_length=20, null=True),
        ),
    ]
