# Generated by Django 5.1.7 on 2025-06-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fingerprint_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
