# Generated by Django 5.1.7 on 2025-06-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_fingerprint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fingerprint_id',
            field=models.BinaryField(blank=True, max_length=2048, null=True, unique=True),
        ),
    ]
