# Generated by Django 5.1.7 on 2025-06-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_fingerprint_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fingerprint_id',
        ),
        migrations.AddField(
            model_name='user',
            name='fingerprint_id_index',
            field=models.BinaryField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fingerprint_id_little',
            field=models.BinaryField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fingerprint_id_middle',
            field=models.BinaryField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fingerprint_id_ring',
            field=models.BinaryField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fingerprint_id_thumb',
            field=models.BinaryField(blank=True, max_length=2048, null=True),
        ),
    ]
