# Generated by Django 5.1.7 on 2025-06-17 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_fingerprint_id_user_fingerprint_id_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fingerprint_id_index',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fingerprint_id_little',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fingerprint_id_middle',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fingerprint_id_ring',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fingerprint_id_thumb',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CASHIER', 'Cashier'), ('MANAGER', 'Manager'), ('SENIOR_MANAGER', 'Senior Manager'), ('CEO', 'CEO')], default='CASHIER', help_text='Role assigned to the user for permission and filtering.', max_length=20),
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger_type', models.CharField(choices=[('thumb', 'Thumb'), ('index', 'Index'), ('middle', 'Middle'), ('ring', 'Ring'), ('little', 'Little')], help_text='Type of finger registered.', max_length=10)),
                ('fingerprint_data', models.TextField(help_text='Base64 or encoded fingerprint template data.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the fingerprint was registered.')),
                ('user', models.ForeignKey(help_text='The user this fingerprint belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fingerprint',
                'verbose_name_plural': 'Fingerprints',
                'unique_together': {('user', 'finger_type')},
            },
        ),
    ]
