# Generated by Django 5.1.7 on 2025-06-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_fingerprint_id_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fingerprint_id_index',
            field=models.BinaryField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fingerprint_id_little',
            field=models.BinaryField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fingerprint_id_middle',
            field=models.BinaryField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fingerprint_id_ring',
            field=models.BinaryField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fingerprint_id_thumb',
            field=models.BinaryField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('CASHIER', 'Cashier'), ('MANAGER', 'Manager'), ('SENIOR_MANAGER', 'Senior Manager'), ('CEO', 'CEO')], help_text='User role in the system', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Fingerprint',
        ),
    ]
