# Generated by Django 5.1.7 on 2025-06-14 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycashallocation',
            name='allocation_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
