# Generated by Django 5.1.7 on 2025-06-14 15:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0003_alter_congestionentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='congestionentry',
            name='diesel_unit_price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='congestionentry',
            name='total_sales_calculated',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sum of declared diesel + ULP totals', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='congestionentry',
            name='ulp_unit_price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='congestionentry',
            name='diesel_volume_stowe',
            field=models.DecimalField(decimal_places=2, help_text='Diesel liters sold', max_digits=10),
        ),
        migrations.AlterField(
            model_name='congestionentry',
            name='total_cod_sales_value_shift',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='COD value to subtract from expected revenue', max_digits=12),
        ),
        migrations.AlterField(
            model_name='congestionentry',
            name='ulp_volume_stowe',
            field=models.DecimalField(decimal_places=2, help_text='ULP liters sold', max_digits=10),
        ),
    ]
