# Generated by Django 5.1.7 on 2025-06-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0004_congestionentry_diesel_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Set true when shift has been reviewed or finalized'),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_number',
            field=models.PositiveIntegerField(blank=True, help_text='Optional manual or system-assigned sequential shift number', null=True),
        ),
    ]
