# Generated by Django 5.1.7 on 2025-06-15 13:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0005_shift_confirmed_shift_shift_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congestionentry',
            name='shift',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='congestion_entry', to='reconciliation.shift'),
        ),
        migrations.AlterField(
            model_name='congestionentry',
            name='total_cod_sales_value_shift',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='COD value to subtract from actual received cash', max_digits=12),
        ),
        migrations.DeleteModel(
            name='CashSubmission',
        ),
    ]
