# Generated by Django 5.1.7 on 2025-06-15 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0006_alter_congestionentry_shift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fueladjustment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='fueladjustment',
            name='adjustment_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
