# Generated by Django 5.1.7 on 2025-06-15 16:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0007_remove_fueladjustment_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelorder',
            name='buying_price_per_liter',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Purchase price per liter from the supplier', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelorder',
            name='cost_paid_rands',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total value paid for the order (buying_price × quantity)', max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fuelorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Senior Manager or CEO who approved this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_orders_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuelorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this order record was created'),
        ),
        migrations.AlterField(
            model_name='fuelorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, help_text='Expected delivery date from supplier', null=True),
        ),
        migrations.AlterField(
            model_name='fuelorder',
            name='fuel_type',
            field=models.CharField(choices=[('ULP', 'Unleaded Petrol'), ('Diesel', 'Diesel'), ('Oil', 'Oil')], help_text='Type of fuel being ordered (e.g. ULP, Diesel)', max_length=10),
        ),
        migrations.AlterField(
            model_name='fuelorder',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional remarks or context', null=True),
        ),
        migrations.AlterField(
            model_name='fuelorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date the order was placed'),
        ),
        migrations.AlterField(
            model_name='fuelorder',
            name='ordered_by',
            field=models.ForeignKey(help_text='User who placed the order', on_delete=django.db.models.deletion.PROTECT, related_name='fuel_orders_placed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuelorder',
            name='quantity_ordered_liters',
            field=models.DecimalField(decimal_places=2, help_text='Quantity of fuel ordered in liters', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fuelorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved (Sent to Supplier)'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Fully Received'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Lifecycle status of the order', max_length=20),
        ),
        migrations.AlterField(
            model_name='fuelorder',
            name='supplier_name',
            field=models.CharField(blank=True, help_text='Optional supplier name for reference', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional uploaded file: reconciliation sheet, fuel log, etc.', null=True, upload_to='shift_attachments/'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='cashier',
            field=models.ForeignKey(help_text='Cashier assigned to this shift', limit_choices_to={'role': 'CASHIER'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shift',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Marked true when the shift has been reviewed and signed off'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_datetime',
            field=models.DateTimeField(help_text='End timestamp for the shift'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='sales_data_confirmed_by_cashier',
            field=models.BooleanField(default=False, help_text='Has the cashier reviewed and approved the sales totals?'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_number',
            field=models.PositiveIntegerField(blank=True, help_text='Optional manual or auto-generated number to identify the shift sequence', null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.IntegerField(choices=[(1, 'Shift 1 (5:00 AM – 10:00 AM)'), (2, 'Shift 2 (10:00 AM – 4:00 PM)'), (3, 'Shift 3 (4:00 PM – 9:00 PM)')], help_text='The type or time block of the shift'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='source_of_data',
            field=models.CharField(default='STOWE', help_text='System or source that provided the initial shift data', max_length=50),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_datetime',
            field=models.DateTimeField(help_text='Start timestamp for the shift'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='stowe_shift_id',
            field=models.CharField(help_text='STOWE-provided identifier for this shift', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of last update'),
        ),
    ]
