# Generated by Django 5.1.7 on 2025-06-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0008_fuelorder_buying_price_per_liter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='final_variance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final reconciled variance (expected - actual), synced from congestion entry', max_digits=12, null=True),
        ),
    ]
