# Generated by Django 5.1.7 on 2025-06-16 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0009_shift_final_variance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fueltank',
            options={'ordering': ['fuel_type'], 'verbose_name': 'Fuel Tank', 'verbose_name_plural': 'Fuel Tanks'},
        ),
        migrations.AddField(
            model_name='diprecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fueltank',
            name='is_stowe_verified',
            field=models.BooleanField(default=False, help_text='Indicates whether the current level has been cross-checked with STOWE'),
        ),
        migrations.AlterField(
            model_name='fueltank',
            name='capacity_liters',
            field=models.DecimalField(decimal_places=2, help_text='Maximum storage capacity in liters', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fueltank',
            name='current_liters',
            field=models.DecimalField(decimal_places=2, help_text='Manually updated current tank level in liters (based on STOWE dips)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fueltank',
            name='fuel_type',
            field=models.CharField(help_text="Type of fuel stored in the tank (e.g. 'ULP', 'Diesel')", max_length=50),
        ),
        migrations.AlterField(
            model_name='fueltank',
            name='last_reconciliation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the latest confirmed dip or tank level update'),
        ),
    ]
