# Generated by Django 5.1.7 on 2025-06-16 17:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0010_alter_fueltank_options_diprecord_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='diprecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this dip record was logged'),
        ),
        migrations.AlterField(
            model_name='diprecord',
            name='dip_reading_liters',
            field=models.DecimalField(decimal_places=2, help_text='Physical measurement of fuel level in liters', max_digits=10),
        ),
        migrations.AlterField(
            model_name='diprecord',
            name='dip_type',
            field=models.CharField(choices=[('OPENING', 'Opening Dip'), ('CLOSING', 'Closing Dip'), ('INTERIM', 'Interim Check')], help_text='Type of dip: Opening, Closing, or Interim', max_length=10),
        ),
        migrations.AlterField(
            model_name='diprecord',
            name='fuel_tank',
            field=models.ForeignKey(help_text='Tank this dip reading corresponds to', on_delete=django.db.models.deletion.PROTECT, related_name='dip_records', to='reconciliation.fueltank'),
        ),
        migrations.AlterField(
            model_name='diprecord',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes or context for this reading', null=True),
        ),
        migrations.AlterField(
            model_name='diprecord',
            name='record_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the dip was recorded'),
        ),
        migrations.AlterField(
            model_name='diprecord',
            name='recorded_by',
            field=models.ForeignKey(help_text='User who recorded the dip', on_delete=django.db.models.deletion.PROTECT, related_name='dip_records_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DailyFuelSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('ulp_sold_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diesel_sold_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cod_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reconciliation.shift')),
            ],
            options={
                'ordering': ['sale_date'],
                'unique_together': {('sale_date', 'shift', 'cashier')},
            },
        ),
    ]
