# Generated by Django 5.1.7 on 2025-05-27 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Morning Shift, Night Shift', max_length=100)),
                ('start_time', models.TimeField(help_text='Shift start time')),
                ('end_time', models.TimeField(help_text='Shift end time')),
            ],
        ),
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique employee identifier', max_length=50, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Exact time of the event')),
                ('is_manual_adjustment', models.BooleanField(default=False, help_text='True if this record was manually adjusted/created')),
                ('notes', models.TextField(blank=True, help_text='Reason for manual adjustment or any other notes', null=True)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_ins', to='attendance.attendant')),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Exact time of the event')),
                ('is_manual_adjustment', models.BooleanField(default=False, help_text='True if this record was manually adjusted/created')),
                ('notes', models.TextField(blank=True, help_text='Reason for manual adjustment or any other notes', null=True)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_outs', to='attendance.attendant')),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HourlyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Hourly wage rate', max_digits=8)),
                ('effective_date', models.DateField(help_text='Date from which this rate is effective')),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_rates', to='attendance.attendant')),
            ],
            options={
                'ordering': ['attendant', '-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjusted_clock_in', models.DateTimeField(blank=True, help_text='Manually set clock-in time', null=True)),
                ('adjusted_clock_out', models.DateTimeField(blank=True, help_text='Manually set clock-out time', null=True)),
                ('reason', models.TextField(help_text='Reason for the adjustment')),
                ('adjustment_timestamp', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(help_text='Manager who made the adjustment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_adjustments', to=settings.AUTH_USER_MODEL)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_adjustments', to='attendance.attendant')),
                ('original_clock_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments_made', to='attendance.clockin')),
                ('original_clock_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments_made', to='attendance.clockout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the shift')),
                ('notes', models.TextField(blank=True, null=True)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='attendance.attendant')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_attendants', to='attendance.shift')),
            ],
            options={
                'ordering': ['date', 'shift__start_time'],
                'unique_together': {('attendant', 'date', 'shift')},
            },
        ),
    ]
