# Generated by Django 5.1.7 on 2025-05-27 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='attendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_ins', related_query_name='clock_in', to='attendance.attendant'),
        ),
        migrations.AlterField(
            model_name='clockout',
            name='attendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_outs', related_query_name='clock_out', to='attendance.attendant'),
        ),
    ]
